language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    #- os: osx
    #  osx_image: xcode8

addons:
  apt:
    packages:
      - g++-multilib
      - lib32stdc++6

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

install:
  - ./gradlew assemble

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build


