version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: gradlew.bat build
artifacts:

- path: build/snobotSim.jar
  name: snobotSimJar

- path: build/snobotSimGui.jar
  name: snobotSimGui

- path: build/snobotSimLibrary-windows.jar
  name: snobotSimNativeLibraryJar

- path: build/snobotSimCppSources.zip
  name: snobotSimCppSources

- path: build/snobotSimJavaDependencies.zip
  name: snobotSimJavaDependencies

- path: build/snobotSimLibrary-windows.zip
  name: snobotSimNativeLibraryZip
