version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: gradlew.bat build
artifacts:

- path: snobotSim.jar
  name: snobotSimJar

- path: snobotSimGui.jar
  name: snobotSimGui

- path: snobotSimLibrary-windows.jar
  name: snobotSimNativeLibraryJar

- path: snobotSimCppSources.zip
  name: snobotSimCppSources

- path: snobotSimJavaDependencies.zip
  name: snobotSimJavaDependencies

- path: snobotSimLibrary-windows.zip
  name: snobotSimNativeLibraryZip
