version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: gradlew.bat build publish -Pmaven_repo=build/maven_repo
artifacts:

- path: build/snobotSim.jar
  name: snobotSim

- path: build/snobotSim-gui.jar
  name: snobotSim-gui

- path: build/snobotSim-NativeJava-windows.jar
  name: snobotSim-NativeJava-windows

- path: build/snobotSim-cpp-sources.zip
  name: snobotSim-cpp-sources

- path: build/snobotSim-javadeps.zip
  name: snobotSim-javadeps

- path: build/snobotSim-NativeCpp-windows.zip
  name: snobotSim-NativeCpp-windows

- path: native/snobot_sim_gui/build/distributions
  name: SnobotSimulator

- path: build/maven_repo
  name: MavenStuff
