version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: gradlew.bat build publish -Pmaven_repo=build/maven_repo
artifacts:

- path: build/maven_repo/com/snobot/simulator/snobotSim/**/snobotSim*.jar
  name: snobotSimJars

- path: build/maven_repo/com/snobot/simulator/snobotSim/**/snobotSim*.zip
  name: snobotSimZips

- path: build/maven_repo/com/snobot/simulator/snobotSimApplication/**/snobotSimApplication*.zip
  name: snobotApplication

- path: build/maven_repo
  name: MavenStuff
